---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Release.Namespace }}
  labels:
    app: ollama
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ollama
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 11434
