apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: postgres
    release: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.credentials.user | b64enc | quote }}

  {{- if .Values.credentials.password }}
  POSTGRES_PASSWORD: {{ .Values.credentials.password | b64enc | quote }}
  {{- end }}

  POSTGRES_DB: {{ .Values.credentials.database | b64enc | quote }}
