---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: admin
    release: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
