---
apiVersion: v1
kind: Secret
metadata:
  name: game-server-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: game-server
    release: {{ .Release.Name }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.GOOGLE_CLIENT_ID | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET | b64enc | quote }}
