---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: frontend
    release: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
