---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: frontend
    release: {{ .Release.Name }}
type: Opaque
data:
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET | b64enc | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | b64enc | quote }}
