---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
